### PR TITLE
Add map argument for php backend

### PR DESCRIPTION
**Pull request by AaronHolbrook**
Tested this locally and it works simply by appending `?xdebug=on` as a query arg to the url.

### CODE REVIEW

**Comment by AaronHolbrook** [comment]
This is for #13

**Comment by philipnewcomer** [comment]
@AaronHolbrook just want to confirm - does the query var override the xdebug cookie if the cookie is present, or the other way around?

**Comment by philipnewcomer** [comment]
Does this also allow you to force xdebug off if the cookie is enabling it? I think we'd want there to be three states: default (respect the cookie), forced on, and forced off.

**Comment by AaronHolbrook** [comment]
I'm not sure which takes precedence.

I think, although will have to test to confirm, that it is simply if either is present it will use xdebug. If either is present it will use, and only if neither will it not use

**Comment by AaronHolbrook** [comment]
Yea would need to add a map for the off value

**Comment by AaronHolbrook** [comment]
Upon further testing, having multiple map statements like this both setting a default value does not work. The latter map overrides the initial one. I will continue working on this and update this PR when I have a working solution

**Comment by AaronHolbrook** [comment]
This is now resolved, with the argument overriding the cookie (on and off). This works with both enabled, both removed, and with cookie on and argument setting to off.

Used this as the guide: http://stackoverflow.com/questions/30078679/nginx-conf-w-multiple-maps-to-same-variable

**Comment by AaronHolbrook** [comment]
Having a temporary variable which is then set in the second map statement is the only way I could get this to work, tried using the set statement, multiple if statements, nothing else was successful.

**Pull request merged**
